/* ================= RAY CREDIT & COLLECTIONS · actions ================= */
const onRAY = () => route().startsWith('raahi');
const rr = () => { render(); if(document.getElementById('wa-root').innerHTML) waRender(); };

A.pauseToggle=()=>{
  if(S.paused){S.paused=false;log({ic:'play',ti:'RAY resumed',de:'New actions can be drafted again',src:[],who:M.owner+' · Dashboard'});rr();toast('RAY resumed');return}
  modal({title:'Pause RAY?',body:`<p style="color:var(--strong)">Stops new RAY actions immediately. Existing payments continue normally.</p><p class="muted small mt8">Drafted reminders stay as drafts. RAY on WhatsApp and Ray AI will still answer questions, but won’t send or change anything.</p>`,actions:[{label:'Cancel'},{label:'Pause RAY',cls:'btn-d',fn:()=>{closeModal();S.paused=true;log({ic:'pause',ti:'RAY paused',de:'No new actions until resumed',src:[],who:M.owner+' · Dashboard'});rr();toast('RAY paused')}}]});
};
A.sync=(btn)=>{btn.outerHTML=thinking('Syncing with Marg ERP…');setTimeout(()=>{S.stale=false;log({ic:'refresh',ti:'Ledger synced from Marg ERP',de:`${pfStats().openInvoices.toLocaleString('en-IN')} open invoices · reminders and approvals resumed`,src:['led'],who:'Marg ERP connector'});rr();toast('Marg ERP synced · reminders resumed')},1500)};
A.keepTerms=()=>A.keepLimit();

A.routineMode=()=>{ if(S.ctl.auto==='routine') return; modal({title:'Let RAY send routine reminders on its own?',body:`<p class="muted">RAY will send low-risk routine reminders to Reliable buyers without asking first. Quiet hours and weekly limits still apply.</p><div class="col gap6 mt12 small">${['Credit limits and payment terms','Pausing supply','Bulk communication','Anything for Watch or Risky buyers'].map(x=>`<div class="lockline">${I('lock',14)}${x} still need your approval</div>`).join('')}</div>`,actions:[{label:'Cancel'},{label:'Turn on routine reminders',cls:'btn-p',fn:()=>{closeModal();S.ctl.auto='routine';log({ic:'gear',ti:'Routine reminders turned on',de:'Reliable buyers only · quiet hours and weekly limits apply',src:[],who:M.owner+' · Controls'});rr();toast('Routine reminders on')}}]}); };
A.netToggle=()=>{ if(S.ctl.net){ S.ctl.net=false; log({ic:'users',ti:'Left Razorpay network signal',de:'Network signals no longer used · RAY continues with your data',src:[],who:M.owner+' · Controls'}); rr(); toast('Razorpay network signal turned off'); return; }
  modal({title:'Join Razorpay network signal?',body:`<p class="muted">Learn how your buyers repay other distributors on Razorpay. RAY warns earlier, catches hidden risk and gives new buyers a fair limit from day one.</p><div class="col gap6 mt12 small">${['Other distributors’ names, invoices and transactions are never shown','Signals are aggregated and privacy-preserving','Used only for buyers who have consented','You can turn this off anytime','Appropriate consent and compliance requirements apply'].map(x=>`<div class="row gap8" style="align-items:flex-start"><span style="color:var(--g);margin-top:1px;flex-shrink:0">${I('check',14,2.4)}</span>${x}</div>`).join('')}</div>`,actions:[{label:'Cancel'},{label:'Join Razorpay network signal',cls:'btn-p',fn:()=>{closeModal();S.ctl.net=true;log({ic:'users',ti:'Joined Razorpay network signal',de:'Opted in by merchant · aggregated signals only',src:['net'],who:'Approved by '+M.owner+' · Controls'});rr();toast('Razorpay network signal on')}}]}); };
A.approveGupta=()=>{const g=S.gupta, r=recOf('gupta'), over=g.out-r.recommendedLimit;
  if(r.recommendedLimit===g.limit&&r.recommendedTerms===g.curTerms&&!recChanged('gupta')) return toast('Nothing to approve · the current limit already matches RAY’s recommendation');
  modal({title:`Set Gupta Traders’ future credit limit to ${inr(r.recommendedLimit)}?`,body:`
   <div class="col gap8 mt8">${[['shield',`Future limit ${inr(r.recommendedLimit)} · ${r.recommendedTerms}-day terms`,`From ${inr(g.limit)} · ${g.curTerms} days · applies to new invoices only`],over>0?['info',`Currently ${inr(over)} above the proposed limit`,'That amount stays due. RAY will flag any additional credit request for your approval. Existing supply is not paused automatically.']:['check','Outstanding is within the proposed limit','Existing supply is not paused automatically.'],['clock','Follow-up starts 7 days before each due date','RAY drafts it early. You still approve before it is sent.']].map(x=>`<div class="row gap12" style="padding:14px 16px;border:1px solid var(--border);border-radius:10px;align-items:flex-start"><span style="width:32px;height:32px;border-radius:8px;background:var(--blue-tint);color:var(--link);display:grid;place-items:center;flex-shrink:0">${I(x[0],17)}</span><div><div style="font-weight:600;color:var(--strong)">${x[1]}</div><div class="xs muted mt4">${x[2]}</div></div></div>`).join('')}</div>
   <div class="xs muted mt12">${r.band} · confidence ${r.confidence} · policy ${r.policyVersion}. The change is written to your ledger only after you confirm. You can undo it, and it is logged in Activity.</div>`,
   actions:[{label:'Cancel'},{label:`Set future limit to ${inr(r.recommendedLimit)}`,cls:'btn-p',id:'set-limit',disabled:blocked(),fn:()=>{closeModal();approveGuptaDo(prMob()?'RAY Credit for Mobile':'Dashboard')}}]})};
function approveGuptaDo(via,noSetup){
  const g=S.gupta, r=recOf('gupta'); if(g.rec==='approved'&&!recChanged('gupta')) return; if(blocked()) return toast(S.paused?'RAY is paused':'Ledger is stale · sync before approving');
  g.prevLimit=g.limit; g.prevTerms=g.curTerms; const inc=r.recommendedLimit>g.limit;
  setLimitValue('gupta', r.recommendedLimit, r.recommendedTerms);
  recordEvent({type:'CREDIT_APPROVED', buyerId:'gupta', source:via, actor:M.owner, meta:{limit:r.recommendedLimit, terms:r.recommendedTerms, from:g.prevLimit, increase:inc, policy:r.policyVersion}},{quiet:true});
  decide('gupta','approved',via);
  g.rec='approved'; g.approvedVia=via; g.approvedAt=simDateLabel()+', '+nowT(); S.later.gupta=false;
  log({ic:'check',ti:`Gupta Traders: future limit set to ${inr(g.limit)} · ${g.curTerms}-day terms`,de:`Was ${inr(g.prevLimit)} · ${g.prevTerms} days · ${r.band} · policy ${r.policyVersion} · new credit above the limit needs approval · supply continues`,src:['led',r.network.eligible?'net':'rzp','conv'],who:`Approved by ${M.owner} · ${via}`,chem:'Gupta Traders'});
  if(!S.req.gupta&&via!=='Ray AI') S.req.gupta='limit';
  rr(); toast(`Future limit set to ${inr(g.limit)} · logged in Activity`);
  if(!noSetup&&(via==='Dashboard'||via==='RAY Credit for Mobile')&&!S.mand.gupta) setTimeout(()=>A.repaySetup('gupta',g.limit,g.curTerms),350);
}
A.undoGupta=()=>{const g=S.gupta; setLimitValue('gupta', g.prevLimit||100000, g.prevTerms||30); const d=decOf('gupta'); if(d.hist[0]){ d.snap=d.hist[0].from; d.hist.shift(); } d.status='baseline'; g.rec='open';
  log({ic:'refresh',ti:'Gupta Traders limit change undone',de:`Back to ${inr(g.limit)} · ${g.curTerms} days`,src:['conv'],who:M.owner+' · Dashboard',chem:'Gupta Traders'}); rr(); toast('Undone · limit restored');};
const reasonPick = (opts) => `<div class="col gap8 mt12">${opts.map((r,i)=>`<button class="radio-card ${i===0?'on':''}" style="padding:12px 14px" onclick="this.parentNode.querySelectorAll('.radio-card').forEach(x=>x.classList.remove('on'));this.classList.add('on')"><span class="radio"></span>${r}</button>`).join('')}</div>`;
A.keepLimit=()=>{const g=S.gupta; modal({title:'Keep the current limit for Gupta Traders?',body:`<p class="muted">The limit stays ${inr(g.limit)} on ${g.curTerms}-day terms and deliveries continue as usual. Tell RAY why, so the override is on record.</p>${reasonPick(['I’ve spoken to Gupta ji directly','Relationship reasons','The signals look wrong'])}`,actions:[{label:'Cancel'},{label:'Keep current limit',cls:'btn-p',fn:()=>{const why=(document.querySelector('.modal .radio-card.on')||{}).textContent||'';closeModal();recordEvent({type:'CREDIT_KEPT', buyerId:'gupta', source:'Dashboard', actor:M.owner, meta:{reason:why}},{quiet:true});decide('gupta','kept');g.rec='kept';g.alert=false;g.kept=true;log({ic:'check',ti:'Kept current limit for Gupta Traders',de:`Merchant override · ${inr(g.limit)} · ${g.curTerms} days · reason: ${why} · RAY keeps watching`,src:['conv'],who:'Decided by '+M.owner+' · Dashboard',chem:'Gupta Traders'});rr();toast('Current limit kept · override recorded')}}]});};
A.editGupta=()=>A.keepLimit(); A.dismissGupta=()=>A.keepLimit();
A.setLimit=(id)=>{const c=chemView(chem(id)), r=recOf(id), lim=r.recommendedLimit, over=c.out-lim;
  modal({title:`Set ${c.name}’s future credit limit to ${inr(lim)}?`,body:`<div class="kvline" style="border:0"><span>Current limit</span><b class="num">${inr(c.limit)} · ${curTermsOf(id)} days</b></div><div class="kvline"><span>Future limit</span><b class="num">${inr(lim)} · ${r.recommendedTerms} days</b></div><div class="kvline"><span>Applies to</span><b>New invoices only</b></div><div class="kvline"><span>Why</span><b style="font-weight:500;text-align:right;max-width:60%">${shortReasons(id).join(' · ')}</b></div>${over>0?`<div class="ol-note mt12"><span style="color:var(--a);flex-shrink:0">${I('info',15,2)}</span><span>${c.name} is currently <b class="num">${inr(over)}</b> above the proposed limit. That amount stays due. RAY will flag any additional credit request for approval. Existing supply is not paused automatically.</span></div>`:''}`,
   actions:[{label:'Cancel'},{label:`Set future limit to ${inr(lim)}`,cls:'btn-p',disabled:blocked(),fn:()=>{closeModal();const was=c.limit;setLimitValue(id,lim,r.recommendedTerms);recordEvent({type:'CREDIT_APPROVED', buyerId:id, source:'Dashboard', actor:M.owner, meta:{limit:lim, terms:r.recommendedTerms, from:was, increase:lim>was, policy:r.policyVersion}},{quiet:true});decide(id,'approved','Dashboard');log({ic:'check',ti:`${c.name}: future limit set to ${inr(lim)}`,de:`Was ${inr(was)} · ${r.band} · policy ${r.policyVersion} · new credit above the limit needs approval`,src:['led','rzp'],who:'Approved by '+M.owner+' · Dashboard',chem:c.name});rr();toast('Future limit set · logged in Activity');if(lim>was&&!S.mand[id]) setTimeout(()=>A.repaySetup(id,lim,r.recommendedTerms),350);}}]});};
A.keepLimitG=(id)=>{const c=chem(id); recordEvent({type:'CREDIT_KEPT', buyerId:id, source:'Dashboard', actor:M.owner},{quiet:true}); decide(id,'kept'); log({ic:'check',ti:`Kept current limit for ${c.name}`,de:'Merchant override · recorded with the recommendation it overrides',src:['conv'],who:'Decided by '+M.owner+' · Dashboard',chem:c.name}); rr(); toast('Current limit kept · override recorded');};

/* ---- credit check · New Life Stores: consent is requested, then answered by the buyer ---- */
A.lookup=()=>{const el=document.getElementById('idq'); const raw=el?(el.value||'03AANFN7781K1Z3'):''; const d=detectId(raw); S.check={step:'looking',q:raw,by:d.by,who:d.who}; rr();
  setTimeout(()=>{ if(d.who==='newlife'&&!S.newLife){ const c=sigOf('newlife').consent; if(!netOn()){ S.check.step='result'; S.check.core=true; } else if(c==='available'){ S.check.step='result'; S.check.core=false; } else if(c==='pending'){ S.check.step='waiting'; } else { S.check.step='found'; S.check.declined=c==='denied'||c==='revoked'; } } else S.check.step='known'; rr()},1000)};
A.sendConsent=()=>{ recordEvent({type:'CONSENT_REQUESTED', buyerId:'newlife', source:'WhatsApp via RAY', actor:M.owner}); S.check.step='waiting'; S.check.sentAt=nowT();
  log({ic:'lock',ti:'Consent request sent to New Life Stores',de:'WhatsApp · to the number on its GST record · buyer can decline or withdraw anytime',src:['conv'],who:'Sent by '+M.owner+' · Dashboard'}); rr(); };
A.consentReply=(ok)=>{ recordEvent({type:ok?'CONSENT_GRANTED':'CONSENT_DENIED', buyerId:'newlife', source:'WhatsApp', actor:'New Life Stores (simulated)'});
  log({ic:ok?'check':'ban',ti:ok?'New Life Stores approved consent':'New Life Stores declined consent',de:ok?'Aggregated repayment record can be used for this credit check':'Network not used · own-data starter recommendation',src:ok?['net']:['conv'],who:'Buyer · WhatsApp (simulated)'});
  S.check.step='analysing'; S.check.core=!ok; S.check.edited=false; rr(); setTimeout(()=>{ if(S.check.step==='analysing'){ S.check.step='result'; rr(); } },900); };
const nlLimit = () => S.check.edited?S.check.limit:recOf('newlife').recommendedLimit;
const nlTerms = () => S.check.edited?S.check.terms:recOf('newlife').recommendedTerms;
A.approveTerms=()=>{ const L=nlLimit(), T=nlTerms(); modal({title:`Extend ${inr(L)} credit to New Life Stores?`,body:`<div class="kvline" style="border:0"><span>Credit limit</span><b class="num">${inr(L)}</b></div><div class="kvline"><span>Payment terms</span><b>${T} days</b></div><div class="kvline"><span>Basis</span><b>${recOf('newlife').networkStep?'Starter policy + consented network uplift':'Starter policy (your data only)'}</b></div><div class="kvline"><span>Where</span><b>Added to Marg ERP as a new party</b></div><p class="xs muted mt12">RAY will start tracking New Life Stores’s payment behaviour from the first invoice.</p>`,actions:[{label:'Cancel'},{label:`Extend ${inr(L)} credit`,cls:'btn-p',disabled:blocked(),fn:()=>{closeModal();S.check.step='approved';S.newLife=true;setLimitValue('newlife',L,T);recordEvent({type:'CREDIT_APPROVED', buyerId:'newlife', source:'Dashboard', actor:M.owner, meta:{limit:L, terms:T, from:0, increase:false, policy:POL.version}},{quiet:true});decide('newlife','approved');log({ic:'check',ti:'Credit terms approved for New Life Stores',de:`${inr(L)} · ${T} days · added to Marg ERP${S.check.edited?' · edited by you':''}`,src:recOf('newlife').networkStep?['net','rzp']:['rzp'],who:'Approved by '+M.owner+' · Dashboard',chem:'New Life Stores'});rr();toast('New Life Stores added to your buyers');setTimeout(()=>A.repaySetup('newlife',L,T),350);}}]}); };
A.editTerms=()=>modal({title:'Edit credit terms',body:`<div class="field"><label>Credit limit (₹)</label><input class="input num" id="et-l" value="${nlLimit()}"></div><div class="field mt16"><label>Payment terms</label><select class="select" id="et-t">${[7,15,21,30].map(d=>`<option value="${d}" ${nlTerms()===d?'selected':''}>${d} days</option>`).join('')}</select></div><p class="xs muted mt12">RAY recommended ${inr(recOf('newlife').recommendedLimit)} · ${recOf('newlife').recommendedTerms} days. Your edit is logged with the decision.</p>`,actions:[{label:'Cancel'},{label:'Save',cls:'btn-p',fn:()=>{const v=parseInt(document.getElementById('et-l').value.replace(/\D/g,''));if(!v||v<0||v>10000000){toast('Enter a valid limit');return;}S.check.limit=v;S.check.terms=+document.getElementById('et-t').value;S.check.edited=true;closeModal();rr()}}]});

/* ---- chase: every send goes through the controls gate, at draft time and again at send time ---- */
A.chaseSet=(id,st)=>{S.chase[id].st=st; if(st==='skipped') log({ic:'skip',ti:`Action dismissed for ${chem(id).name}`,de:'Will reappear in Actions tomorrow if still due',src:[],who:M.owner+' · Dashboard',chem:chem(id).name}); rr()};
A.saveEdit=id=>{S.chase[id].msg=document.getElementById('ed-'+id).value;S.chase[id].by='you';S.chase[id].editing=false;rr();toast('Draft updated')};
const chaseInv = id => { const n=nextDueInv(id); return id==='gupta'?'INV-24891':n?n.inv:null; };
function checksLine(id, g){ if(S.stale) return `<span style="color:var(--a);font-weight:600">Ledger last synced 31 hours ago. RAY can’t confirm payment status until it is refreshed.</span>`;
  return `RAY checked Razorpay payments${S.bank.st==='on'?', your bank feed':''}, unidentified credits and salesperson collections. ${g&&g.action==='block'?'':'No matching payment found.'} Quiet hours ${S.ctl.qf}–${S.ctl.qt} IST and max ${S.ctl.max} apply.`; }
A.approveOne=id=>{const c=chaseOf(id), ch=chem(id);
  if(c.ch==='sm') return A.assignTo(id);
  const lab=ctaLabel(c), early=c.kind==='Early follow-up', inv=chaseInv(id), g=gateFor(id,'whatsapp',inv);
  const ten=RayDates.istMs(S.today,600), canSchedule=simNowMs()<ten;
  modal({title:early?`Start early follow-up with ${ch.name}?`:`Send reminder to ${ch.name}?`,body:`<div class="small muted">To ${ch.name} · +91 98XXX XX${(ch.name.length*7)%90+10} · WhatsApp via RAY’s verified Razorpay account</div><div class="wa-preview mt12"><div class="wa-bubble">${esc(S.chase[id].msg)}<span class="lnk">${LINK(id)}</span></div></div>
   ${g.action==='block'?`<div class="alert warn mt12" style="padding:12px 14px"><span class="ic" style="width:28px;height:28px">${I('ban',15)}</span><div class="small grow"><b style="color:var(--strong)">Can’t send this now.</b> ${esc(gateNote(g))}</div></div>`
     :`<div class="col gap8 mt16"><button class="radio-card send-when on" data-w="now" style="padding:12px 14px" onclick="this.parentNode.querySelectorAll('.radio-card').forEach(x=>x.classList.remove('on'));this.classList.add('on')"><span class="radio"></span>${g.action==='queue'?'Queue for the end of quiet hours':'Send now'}</button>${canSchedule?`<button class="radio-card send-when" data-w="10" style="padding:12px 14px" onclick="this.parentNode.querySelectorAll('.radio-card').forEach(x=>x.classList.remove('on'));this.classList.add('on')"><span class="radio"></span>Send at 10:00 AM <span class="xs muted">· best response window for this buyer</span></button>`:''}</div>${g.action==='queue'?`<div class="xs mt8" style="color:#9a5b00;font-weight:600">${esc(gateNote(g))}</div>`:''}`}
   <div class="xs muted mt12">${checksLine(id,g)}</div>`,
   actions:[{label:'Cancel'},{label:g.action==='block'?'Blocked by your controls':lab,cls:'btn-p',id:'send-one',disabled:g.action==='block'||blocked(),fn:()=>{const w=(document.querySelector('.send-when.on')||{}).dataset; closeModal();
     const r=trySend(id,{kind:early?'followup':'reminder',inv,msg:S.chase[id].msg,via:'Dashboard',scheduleAt:w&&w.w==='10'?ten:null});
     if(r.blocked){ rr(); return toast('Not sent: '+gateNote(r.gate)); }
     const t=nowT(); S.chase[id].st=r.scheduled?'scheduled':r.queued?'queued':'sent'; S.chase[id].at=r.scheduled?'10:00 AM':r.queued?RayDates.fmtTime(RayDates.istParts(r.item.sendAt).min):t;
     log({ic:r.ok?'send':'clock',ti:r.ok?(early?`Early follow-up sent to ${ch.name}`:`Reminder sent to ${ch.name}`):`${early?'Follow-up':'Reminder'} to ${ch.name} ${r.scheduled?'scheduled for 10:00 AM':'queued (quiet hours)'}`,de:`WhatsApp · ${inr(c.amt)} · payment link ${LINK(id)}${r.ok?'':' · controls re-checked at send time'}`,src:['conv'],who:'Approved by '+M.owner+' · Dashboard',chem:ch.name});
     rr(); toast(r.ok?(early?'Follow-up sent to ':'Reminder sent to ')+ch.name:r.scheduled?'Scheduled for 10:00 AM':'Queued until quiet hours end'); if(id==='gupta'&&r.ok) guptaReplySoon()}}]});
};
A.assignTo=(id)=>{const ch=chem(id), c=chaseOf(id)||{id,amt:outOf(id),kind:'Salesperson visit',note:`Collect ${inr(outOf(id))} on the next route visit. WhatsApp is disabled for this buyer.`};
  const g=gateFor(id,'salesperson',chaseInv(id));
  if(g.action==='block'){ return modal({title:'Can’t assign this collection',body:`<p style="color:var(--strong)">${esc(gateNote(g))}</p>`,actions:[{label:'OK',cls:'btn-p'}]}); }
  const cod=c.kind==='Collect before supply', def=id==='bansal'?1:0;
  modal({title:'Assign collection to',body:`<div style="padding:12px 14px;border:1px solid var(--border);border-radius:10px;background:#fbfbfc"><div class="row between"><b style="color:var(--strong)">${ch.name}</b><b class="num">${inr(c.amt)}</b></div><div class="small muted mt4">${ch.area} route · ${cod?'next delivery':'today'}</div><div class="mt8" style="color:var(--strong)">${c.note}</div></div>
   <div class="col gap8 mt16">${SP.map((p,i)=>`<button class="radio-card sp-opt ${i===def?'on':''}" data-p="${p}" style="padding:12px 14px" onclick="document.querySelectorAll('.sp-opt').forEach(x=>x.classList.remove('on'));this.classList.add('on')"><span class="radio"></span><span class="grow"><b style="color:var(--strong)">${p}</b><div class="xs muted">Salesperson</div></span></button>`).join('')}</div>
   ${cod?`<div class="xs muted mt12 row gap4">${I('lock',12)} Supply is never paused automatically. The delivery goes ahead once the amount is collected or you decide otherwise.</div>`:''}`,
   actions:[{label:'Cancel'},{label:cod?'Collect on delivery':'Assign to salesperson',cls:'btn-p',fn:()=>{const p=(document.querySelector('.sp-opt.on')||{}).dataset.p||SP[0]; closeModal(); const r=trySend(id,{channel:'salesperson',kind:'task',via:'Dashboard'}); if(r.blocked) return toast('Not assigned: '+gateNote(r.gate)); S.chaseTo[id]=p; if(S.chase[id]) S.chase[id].st='assigned'; if(id==='mehta') S.mehtaTask=true;
     log({ic:'truck',ti:cod?`Collect on delivery assigned to ${p}`:`Collection assigned to ${p}`,de:`${ch.name} · ${inr(c.amt)} · ${c.note}`,src:['led'],who:'Approved by '+M.owner+' · Dashboard',chem:ch.name});rr();toast('Assigned to '+p)}}]});
};
/* bulk: the count shown is exactly what the gate will allow at execution time */
function bulkPlan(){ syncChase(); const drafts=CHASE.filter(c=>c.ch==='wa'&&S.chase[c.id].st==='draft'); const send=[], queue=[], excluded=[];
  drafts.forEach(c=>{ const g=gateFor(c.id,'whatsapp',chaseInv(c.id)); if(g.action==='send') send.push(c); else if(g.action==='queue') queue.push(c); else excluded.push({c, why:gateNote(g), code:g.code}); });
  CHASE.filter(c=>S.chase[c.id].st==='held').forEach(c=>{ if(!excluded.some(x=>x.c.id===c.id)) excluded.push({c, why:'A recent payment may already cover this. Review it first.', code:'unmatched'}); });
  return {send, queue, excluded}; }
function bulkCounts(){ const p=bulkPlan(); return {wa:p.send.length+p.queue.length, sent:p.send.length, queued:p.queue.length, sm:CHASE.filter(c=>c.ch==='sm'&&S.chase[c.id].st==='draft').length, held:p.excluded.length, excluded:p.excluded}; }
function bulkDo(via){ const t=nowT(); let sent=0, queued=0, blockedN=0; let g=false;
  CHASE.forEach(c=>{const s=S.chase[c.id]; if(s.st!=='draft'||c.ch!=='wa') return; const r=trySend(c.id,{kind:c.kind==='Early follow-up'?'followup':'reminder',inv:chaseInv(c.id),msg:s.msg,via});
    if(r.ok){ s.st='sent'; s.at=t; sent++; if(c.id==='gupta') g=true; } else if(r.queued){ s.st='queued'; s.at=RayDates.fmtTime(RayDates.istParts(r.item.sendAt).min); queued++; } else blockedN++; });
  log({ic:'send',ti:`${sent} WhatsApp reminder${sent===1?'':'s'} sent${queued?` · ${queued} queued for quiet hours`:''}`,de:`Includes early follow-ups · ${blockedN} not sent because of your controls or a pending payment review · controls re-checked at send time`,src:['conv','led'],who:`Approved by ${M.owner} · ${via}`});
  S.wa.sent=true; S.wa.sentVia=via; S.wa.sentAt=t; if(g) guptaReplySoon(); return {wa:sent, queued, held:blockedN};}
A.approveAll=()=>{const p=bulkPlan(), n=p.send.length+p.queue.length;
  modal({title:`Review & send ${n} reminder${n===1?'':'s'}`,body:`<div class="small muted">${p.send.length} ready to send${p.queue.length?` · ${p.queue.length} will be queued for quiet hours`:''}${p.excluded.length?` · ${p.excluded.length} not included`:''}</div>
   <div class="rv-list mt12">${p.send.concat(p.queue).map(c=>`<div class="rv"><span class="nm">${chem(c.id).name}</span><span class="kind k-${(c.kind||'').split(' ')[0].toLowerCase()}">${c.kind}</span><span class="grow"></span><b class="num">${inr(c.amt)}</b></div>`).join('')}</div>
   ${p.excluded.length?`<div class="lbl mt12">Not included</div><div class="col gap4 mt4">${p.excluded.map(x=>`<div class="xs"><b style="color:var(--strong)">${chem(x.c.id).name}</b> · <span class="muted">${esc(x.why)}</span></div>`).join('')}</div>`:''}
   <div class="xs muted mt12">${S.stale?'Ledger is stale, so nothing can be sent until it is refreshed.':'Each message is tailored to the buyer and includes a payment link. Controls are checked again at the moment of sending. Salesperson visits are assigned separately.'}</div>`,
   actions:[{label:'Review individually',fn:()=>{closeModal();A.reviewAll()}},{label:`Send ${n} reminder${n===1?'':'s'}`,cls:'btn-p',id:'bulk-ok',disabled:!n||blocked(),fn:()=>{closeModal();const r=bulkDo('Dashboard');rr();toast(`${r.wa} sent${r.queued?` · ${r.queued} queued`:''}${r.held?` · ${r.held} blocked`:''} · logged in Activity`)}}]});
};
A.reviewAll=()=>{CHASE.forEach(c=>S.chase[c.id].open=c.ch==='wa'||c.held);if(!route().startsWith('raahi/actions')) go('raahi/actions'); else rr(); setTimeout(()=>{const e=document.getElementById('grp-early');e&&e.scrollIntoView({behavior:'smooth',block:'start'})},80)};
A.matchVerma=(btn)=>{btn.outerHTML=thinking('Matching payment…');setTimeout(()=>{S.vermaMatched=true;S.chase.verma.st='matched';recordEvent({type:'PAYMENT_RECONCILED', buyerId:'verma', invoice:'INV-24655', amount:26500, verification:'verified', source:'Razorpay Smart Collect', actor:M.owner, ref:'pay_Q8f2Kx91LmZ4'},{quiet:true});log({ic:'match',ti:'₹26,500 matched to INV-24655',de:'Verma Retail · reminder cancelled, no longer due',src:['rzp','led'],who:'Confirmed by '+M.owner+' · Dashboard',chem:'Verma Retail'});rr();toast('Payment matched · reminder cancelled')},1300)};

/* ---- promise loop: the buyer's reply is interpreted by the AI endpoint (or the labelled fallback) ---- */
const GUPTA_REPLY='Aadha abhi bhej raha hoon, baaki Monday pakka.';
function guptaReplySoon(){ if(S.gupta.promise) return; setTimeout(()=>{ if(S.gupta.promise) return; S.gupta.promise='new';
  log({ic:'chat',ti:'Gupta Traders replied',de:`“${GUPTA_REPLY}”`,src:['conv'],who:'WhatsApp',chem:'Gupta Traders'});
  interpretMessage('gupta',{buyerId:'gupta', buyerName:'Gupta Traders', message:GUPTA_REPLY, inv:'INV-24891', outstanding:balOf('gupta','INV-24891'), messageDate:S.today}).then(st=>{
    if(!S.wa.msgs||!st||st.status!=='done') return; const f=st.fields;
    waPush({from:'ray',html:`Gupta Traders replied:\n<i>“${GUPTA_REPLY}”</i>\n\n${st.mode==='ai'?`I read this (AI · ${st.model})`:'My rule-based parser read this (live AI unavailable)'} as ${f.firstAmt?`<b>${inr(f.firstAmt)} ${f.firstDate===S.today?'today':'on '+RayDates.fmtDay(f.firstDate)}</b>`:'no amount today'}${f.laterAmt?` and <b>${inr(f.laterAmt)} by ${f.laterDate?RayDates.fmtLong(f.laterDate):'an unstated date'}</b>`:''}. Shall I record it?`,btns:[{l:'Confirm',a:'waConfirmPromise'},{l:'Review',a:'waReviewPromise'}]}); });
  if(onRAY()) rr(); toast('Gupta Traders replied to the reminder',{label:'View',fn:()=>go('raahi/activity')}); },3500)}
A.confirmPromise=()=>{ const st=S.interp.gupta; if(!st||st.status!=='done'||S.gupta.promise==='saved') return; A.ipConfirm('gupta'); };
A.editPromise=()=>{ const st=S.interp.gupta; if(!st||st.status!=='done') return; const saved=S.promises.find(p=>p.key==='gupta'&&p.status==='confirmed'); if(saved) return A.ipReopen('gupta');
  const f=st.fields;
  modal({title:'Edit promise',body:`<div class="grid g2"><div class="field"><label>Paying first (₹)</label><input class="input num" id="pe-fa" value="${f.firstAmt??''}"></div><div class="field"><label>On</label><input type="date" class="input" id="pe-fd" min="${S.today}" value="${f.firstDate||S.today}"></div></div><div class="grid g2 mt12"><div class="field"><label>Remaining (₹)</label><input class="input num" id="pe-la" value="${f.laterAmt??''}"></div><div class="field"><label>Promise date</label><input type="date" class="input" id="pe-ld" min="${S.today}" value="${f.laterDate||''}"></div></div><div class="xs mt8" id="pe-err" style="color:var(--r);font-weight:600"></div><p class="xs muted mt8">${inr(balOf('gupta','INV-24891'))} outstanding on INV-24891. Your values are saved exactly as entered.</p>`,
   actions:[{label:'Cancel'},{label:'Save & confirm',cls:'btn-p',fn:()=>{ const n=v=>v===''?null:parseInt(String(v).replace(/[^\d]/g,''),10);
     const nf={firstAmt:n(document.getElementById('pe-fa').value), firstDate:document.getElementById('pe-fd').value||null, laterAmt:n(document.getElementById('pe-la').value), laterDate:document.getElementById('pe-ld').value||null};
     const errs=ipValidate(nf, balOf('gupta','INV-24891')); if(errs.length){ document.getElementById('pe-err').textContent=errs.join(' '); return; }
     closeModal(); st.fields=nf; saveCommitment('gupta', nf, true); }}]}); };
A.reviewJain=()=>modal({title:'Review Jain Traders’ promise',body:`<div class="row gap12" style="padding:12px 14px;background:var(--canvas);border-radius:10px"><span style="width:28px;height:28px;border-radius:50%;background:#fff;border:1px solid var(--border);display:grid;place-items:center">${I('play',11,2)}</span><span class="wa-voice grow"><span class="wave"></span></span><span class="xs muted">0:14</span></div>
   <div class="small mt8"><span class="muted">Transcript:</span> <i>“…Monday…aadha…”</i> <span class="conf-low">${I('alert',12,2.2)} Too little to read reliably</span></div>
   <div class="xs muted mt8">RAY has not filled in a date or amount. Listen, then enter what Jain Traders actually promised.</div>
   <div class="grid g2 mt12"><div class="field"><label>Amount promised (₹)</label><input class="input num" id="jn-a" placeholder="Enter amount" oninput="document.getElementById('jn-ok').disabled=!(this.value&&document.getElementById('jn-d').value)"></div><div class="field"><label>By</label><input type="date" class="input" id="jn-d" min="${S.today}" onchange="document.getElementById('jn-ok').disabled=!(this.value&&document.getElementById('jn-a').value)"></div></div>`,
  actions:[{label:'Cancel'},{label:'Couldn’t tell · ask buyer',fn:()=>{closeModal();S.jainReviewed=true;log({ic:'chat',ti:'Asked Jain Traders to confirm their promise',de:'Voice note unclear · RAY drafted a clarification message · plan unchanged',src:['conv'],who:'Reviewed by '+M.owner,chem:'Jain Traders'});rr();toast('Clarification drafted · plan unchanged')}},{label:'Save promise',cls:'btn-p',id:'jn-ok',disabled:true,fn:()=>{const a=parseInt(document.getElementById('jn-a').value.replace(/\D/g,''))||0, d=document.getElementById('jn-d').value; const inv=nextOpenInv('jain'); if(!a||!d||a>outOf('jain')){toast('Enter an amount up to the outstanding and a date');return;} closeModal();S.jainReviewed=true;
    S.interp['msg:jain']={status:'done',mode:'manual',input:{buyerId:'jain',buyerName:'Jain Traders',message:'Voice note (transcript unclear)',inv:inv.inv,outstanding:inv.bal,messageDate:S.today},interpretation:{intent:'promise',evidenceSpans:[],reasoningSummary:'Entered manually from a voice note.',confidenceLabel:'low'},checks:[],fields:{laterAmt:a,laterDate:d}}; saveCommitment('msg:jain',{firstAmt:null,firstDate:null,laterAmt:a,laterDate:d},true);}}]});

/* ---- simulations ---- */
A.toggleStale=()=>{S.stale=!S.stale; if(S.stale) log({ic:'refresh',ti:'Marg ERP sync delayed',de:'Last synced 31 hours ago · new reminders and approvals paused until refreshed',src:['led'],who:'RAY'}); rr();};
A.reset=()=>{S=S0();_clock=12;if(typeof _wat!=='undefined')_wat=2;persistClear();engInit();A.closeWA();A.aaClose();closeModal();document.getElementById('datechip').textContent='Mon, 5 Oct';go('home');toast('Demo reset')};
